version: '3.5'

services:
  kasbonjs: # Backend Expressjs
    container_name: kasbonjs # Set the container name
    image: kasbonjs:1.0.8
    networks:
      - kasbonnet
    ports:
      - '4000:3000'
      - '4001:3001'
    depends_on:
      - postgres15

  postgres15: # PostgreSQL Database
    container_name: postgres15 # Set the container name
    image: postgres:15
    networks:
      - kasbonnet
    ports:
      - '5442:5432'
    environment:
      POSTGRES_USER: gesangpg
      POSTGRES_PASSWORD: gesangpj01
      POSTGRES_DB: postgres

networks:
  kasbonnet:
    driver: bridge
